language: shell

env:
  global:
    - CONTAINER_NAME=cs8898/docker-android-sdk
    - CONTAINER_TAG=latest

services:
  - docker

script:
  docker build -t $CONTAINER_NAME:$CONTAINER_TAG ./ubuntu/standalone/Dockerfile

deploy:
  provider: script
  script: bash ./.travis/docker_push.sh
  on:
    branch: master
